# Generated by Django 3.0.5 on 2022-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_auto_20221105_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='degree_ed',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='status',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='national_id',
            field=models.CharField(max_length=12),
        ),
    ]
