# Generated by Django 3.0.5 on 2022-12-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0013_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theapp.Patient'),
        ),
    ]
