# Generated by Django 3.0.5 on 2022-11-05 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0006_auto_20221106_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Some address', max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_emergency',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(default='Flu', max_length=100),
        ),
    ]
