# Generated by Django 3.0.5 on 2022-11-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0010_remove_patient_assigneddoctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dentist', 'Dentist'), ('Neurologist', 'Neurologist'), ('Pulmanologist', 'Pulmanologist'), ('Surgeon', 'Surgeon'), ('Labaratory', 'Labaratory'), ('Diagnostics', 'Diagnostics')], default='Cardiologist', max_length=50),
        ),
    ]
