# Generated by Django 3.0.5 on 2022-11-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_auto_20221106_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='Your current address', max_length=40),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree_ed',
            field=models.CharField(choices=[('Doctor of Medicine', 'Doctor of Medicine'), ('Ph.D. in Medicine', 'Ph.D. in Medicine'), ('MD in Medicine', 'MD in Medicine')], default='MD in Medicine', max_length=25),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
