# Generated by Django 3.0.5 on 2022-11-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0008_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/patient_pics'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctor_pics'),
        ),
    ]
