# Generated by Django 4.1.3 on 2022-12-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actor", "0014_alter_appointment_id_alter_doctor_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.CharField(
                choices=[
                    ("Cardiologist", "Cardiologist"),
                    ("Dentist", "Dentist"),
                    ("Neurologist", "Neurologist"),
                    ("Pulmonologist", "Pulmonologist"),
                    ("Surgeon", "Surgeon"),
                    ("Laboratory", "Laboratory"),
                    ("Diagnostics", "Diagnostics"),
                    ("Children", "Children"),
                ],
                default="Cardiologist",
                max_length=50,
            ),
        ),
    ]
